// Single place holding references to every DOM node the app touches.

export const el = {
  heartsRow: document.getElementById('heartsRow'),
  soundToggleBtn: document.getElementById('soundToggleBtn'),
  scoreVal: document.getElementById('scoreVal'),
  bestVal: document.getElementById('bestVal'),
  comboPill: document.getElementById('comboPill'),
  app: document.getElementById('app'),
  card: document.getElementById('card'),
  promptId: document.getElementById('promptId'),
  answerZone: document.getElementById('answerZone'),
  revealBox: document.getElementById('revealBox'),
  revealCompare: document.getElementById('revealCompare'),
  revealSub: document.getElementById('revealSub'),
  wordBank: document.getElementById('wordBank'),
  checkBtn: document.getElementById('checkBtn'),
  nextBtn: document.getElementById('nextBtn'),
  skipBtn: document.getElementById('skipBtn'),
  loadingBox: document.getElementById('loadingBox'),
  errorBox: document.getElementById('errorBox'),
  gameOver: document.getElementById('gameOver'),
  goScore: document.getElementById('goScore'),
  goNewBest: document.getElementById('goNewBest'),
  goCombo: document.getElementById('goCombo'),
  goCorrect: document.getElementById('goCorrect'),
  goBestSmall: document.getElementById('goBestSmall'),
  retryBtn: document.getElementById('retryBtn'),
  shareBtn: document.getElementById('shareBtn'),
  shareHint: document.getElementById('shareHint'),
  shareCard: document.getElementById('shareCard'),
};
